services:
  - type: web
    name: bible-semantic-app
    env: python
    buildCommand: "pip install -r requirements.txt"
    startCommand: "python server.py"
    plan: free
    envVars:
      - key: PYTHON_VERSION
        value: 3.10
